package com.smartMess.pojos;
// Generated Apr 24, 2016 3:13:47 AM by Hibernate Tools 4.3.1



/**
 * Balancetransfer generated by hbm2java
 */
public class Balancetransfer  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private String receiver;
     private double amount;
     private String date;
     private String remark1;
     private String remark2;

    public Balancetransfer() {
    }

	
    public Balancetransfer(Member member, String receiver, double amount, String date) {
        this.member = member;
        this.receiver = receiver;
        this.amount = amount;
        this.date = date;
    }
    public Balancetransfer(Member member, String receiver, double amount, String date, String remark1, String remark2) {
       this.member = member;
       this.receiver = receiver;
       this.amount = amount;
       this.date = date;
       this.remark1 = remark1;
       this.remark2 = remark2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }




}


