package com.smartMess.pojos;
// Generated Apr 24, 2016 3:13:47 AM by Hibernate Tools 4.3.1



/**
 * Images generated by hbm2java
 */
public class Images  implements java.io.Serializable {


     private Integer id;
     private Integer adsId;
     private Integer statusId;
     private String remark1;
     private String remark2;
     private String userid;
     private String imageLink;

    public Images() {
    }

	
    public Images(String imageLink) {
        this.imageLink = imageLink;
    }
    public Images(Integer adsId, Integer statusId, String remark1, String remark2, String userid, String imageLink) {
       this.adsId = adsId;
       this.statusId = statusId;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.userid = userid;
       this.imageLink = imageLink;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getAdsId() {
        return this.adsId;
    }
    
    public void setAdsId(Integer adsId) {
        this.adsId = adsId;
    }
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public String getUserid() {
        return this.userid;
    }
    
    public void setUserid(String userid) {
        this.userid = userid;
    }
    public String getImageLink() {
        return this.imageLink;
    }
    
    public void setImageLink(String imageLink) {
        this.imageLink = imageLink;
    }




}


