package com.smartMess.pojos;
// Generated Apr 24, 2016 3:13:47 AM by Hibernate Tools 4.3.1



/**
 * Locations generated by hbm2java
 */
public class Locations  implements java.io.Serializable {


     private Integer id;
     private String area;
     private String location;
     private String remark1;
     private String remark2;

    public Locations() {
    }

	
    public Locations(String area, String location) {
        this.area = area;
        this.location = location;
    }
    public Locations(String area, String location, String remark1, String remark2) {
       this.area = area;
       this.location = location;
       this.remark1 = remark1;
       this.remark2 = remark2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }




}


