package com.smartMess.pojos;
// Generated Apr 24, 2016 3:13:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Meal generated by hbm2java
 */
public class Meal  implements java.io.Serializable {


     private Integer id;
     private Member member;
     private Date date;
     private double breakFast;
     private double lunch;
     private double dinner;
     private String remark1;
     private String remark2;

    public Meal() {
    }

	
    public Meal(Member member, Date date, double breakFast, double lunch, double dinner) {
        this.member = member;
        this.date = date;
        this.breakFast = breakFast;
        this.lunch = lunch;
        this.dinner = dinner;
    }
    public Meal(Member member, Date date, double breakFast, double lunch, double dinner, String remark1, String remark2) {
       this.member = member;
       this.date = date;
       this.breakFast = breakFast;
       this.lunch = lunch;
       this.dinner = dinner;
       this.remark1 = remark1;
       this.remark2 = remark2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public double getBreakFast() {
        return this.breakFast;
    }
    
    public void setBreakFast(double breakFast) {
        this.breakFast = breakFast;
    }
    public double getLunch() {
         
        return this.lunch;
    
    }
    
    public void setLunch(double lunch) {
        this.lunch = lunch;
    }
    public double getDinner() {
        return this.dinner;
    }
    
    public void setDinner(double dinner) {
        this.dinner = dinner;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }




}


