package com.smartMess.pojos;
// Generated Apr 24, 2016 3:13:47 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private String user;
     private String password;
     private String email;
     private String gender;
     private Date dob;
     private String location;
     private byte[] image;
     private String firstName;
     private String lastName;
     private String messName;
     private String type;
     private String occupation;
     private String remarkMem1;
     private String remarkMem2;
     private Set meals = new HashSet(0);
     private Set moneys = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set notices = new HashSet(0);
     private Set schedules = new HashSet(0);
     private Set tolets = new HashSet(0);
     private Set balancetransfers = new HashSet(0);
     private Set messnames = new HashSet(0);
     private Set statuses = new HashSet(0);

    public Member() {
    }

	
    public Member(String user, String password, String email, String gender, Date dob, String firstName, String lastName, String messName, String type) {
        this.user = user;
        this.password = password;
        this.email = email;
        this.gender = gender;
        this.dob = dob;
        this.firstName = firstName;
        this.lastName = lastName;
        this.messName = messName;
        this.type = type;
    }
    public Member(String user, String password, String email, String gender, Date dob, String location, byte[] image, String firstName, String lastName, String messName, String type, String occupation, String remarkMem1, String remarkMem2, Set meals, Set moneys, Set messages, Set notices, Set schedules, Set tolets, Set balancetransfers, Set messnames, Set statuses) {
       this.user = user;
       this.password = password;
       this.email = email;
       this.gender = gender;
       this.dob = dob;
       this.location = location;
       this.image = image;
       this.firstName = firstName;
       this.lastName = lastName;
       this.messName = messName;
       this.type = type;
       this.occupation = occupation;
       this.remarkMem1 = remarkMem1;
       this.remarkMem2 = remarkMem2;
       this.meals = meals;
       this.moneys = moneys;
       this.messages = messages;
       this.notices = notices;
       this.schedules = schedules;
       this.tolets = tolets;
       this.balancetransfers = balancetransfers;
       this.messnames = messnames;
       this.statuses = statuses;
    }
   
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMessName() {
        return this.messName;
    }
    
    public void setMessName(String messName) {
        this.messName = messName;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public String getRemarkMem1() {
        return this.remarkMem1;
    }
    
    public void setRemarkMem1(String remarkMem1) {
        this.remarkMem1 = remarkMem1;
    }
    public String getRemarkMem2() {
        return this.remarkMem2;
    }
    
    public void setRemarkMem2(String remarkMem2) {
        this.remarkMem2 = remarkMem2;
    }
    public Set getMeals() {
        return this.meals;
    }
    
    public void setMeals(Set meals) {
        this.meals = meals;
    }
    public Set getMoneys() {
        return this.moneys;
    }
    
    public void setMoneys(Set moneys) {
        this.moneys = moneys;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }
    public Set getNotices() {
        return this.notices;
    }
    
    public void setNotices(Set notices) {
        this.notices = notices;
    }
    public Set getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }
    public Set getTolets() {
        return this.tolets;
    }
    
    public void setTolets(Set tolets) {
        this.tolets = tolets;
    }
    public Set getBalancetransfers() {
        return this.balancetransfers;
    }
    
    public void setBalancetransfers(Set balancetransfers) {
        this.balancetransfers = balancetransfers;
    }
    public Set getMessnames() {
        return this.messnames;
    }
    
    public void setMessnames(Set messnames) {
        this.messnames = messnames;
    }
    public Set getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set statuses) {
        this.statuses = statuses;
    }




}


