package com.smartMess.pojos;
// Generated Apr 24, 2016 3:13:47 AM by Hibernate Tools 4.3.1



/**
 * Menus generated by hbm2java
 */
public class Menus  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String type;
     private String link;
     private String remark1;
     private String remark2;
     private String action;

    public Menus() {
    }

	
    public Menus(String name, String type) {
        this.name = name;
        this.type = type;
    }
    public Menus(String name, String type, String link, String remark1, String remark2, String action) {
       this.name = name;
       this.type = type;
       this.link = link;
       this.remark1 = remark1;
       this.remark2 = remark2;
       this.action = action;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }




}


