package com.smartMess.pojos;
// Generated Apr 24, 2016 3:13:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Notice generated by hbm2java
 */
public class Notice  implements java.io.Serializable {


     private Integer idAuto;
     private Member member;
     private Date date;
     private String noticeText;
     private String tag;
     private String remark1;
     private String remark2;

    public Notice() {
    }

	
    public Notice(Member member, Date date, String noticeText) {
        this.member = member;
        this.date = date;
        this.noticeText = noticeText;
    }
    public Notice(Member member, Date date, String noticeText, String tag, String remark1, String remark2) {
       this.member = member;
       this.date = date;
       this.noticeText = noticeText;
       this.tag = tag;
       this.remark1 = remark1;
       this.remark2 = remark2;
    }
   
    public Integer getIdAuto() {
        return this.idAuto;
    }
    
    public void setIdAuto(Integer idAuto) {
        this.idAuto = idAuto;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getNoticeText() {
        return this.noticeText;
    }
    
    public void setNoticeText(String noticeText) {
        this.noticeText = noticeText;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }




}


