package com.smartMess.pojos;
// Generated Apr 24, 2016 3:13:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private Integer idAuto;
     private Member member;
     private Date date;
     private Date bazar;
     private Date toilet;
     private String remark1;
     private String remark2;

    public Schedule() {
    }

	
    public Schedule(Member member, Date date) {
        this.member = member;
        this.date = date;
    }
    public Schedule(Member member, Date date, Date bazar, Date toilet, String remark1, String remark2) {
       this.member = member;
       this.date = date;
       this.bazar = bazar;
       this.toilet = toilet;
       this.remark1 = remark1;
       this.remark2 = remark2;
    }
   
    public Integer getIdAuto() {
        return this.idAuto;
    }
    
    public void setIdAuto(Integer idAuto) {
        this.idAuto = idAuto;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getBazar() {
        return this.bazar;
    }
    
    public void setBazar(Date bazar) {
        this.bazar = bazar;
    }
    public Date getToilet() {
        return this.toilet;
    }
    
    public void setToilet(Date toilet) {
        this.toilet = toilet;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }




}


