package com.smartMess.pojos;
// Generated Apr 24, 2016 3:13:47 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tolet generated by hbm2java
 */
public class Tolet  implements java.io.Serializable {


     private Integer idAuto;
     private Member member;
     private Date date;
     private String description;
     private Integer roomSize;
     private Integer washroom;
     private String title;
     private Integer varanda;
     private Boolean parking;
     private double rent;
     private String contactNumber;
     private String email;
     private String location;
     private String area;
     private String remark1;
     private String remark2;

    public Tolet() {
    }

	
    public Tolet(Member member, Date date, String description, String title, double rent, String contactNumber, String location, String area) {
        this.member = member;
        this.date = date;
        this.description = description;
        this.title = title;
        this.rent = rent;
        this.contactNumber = contactNumber;
        this.location = location;
        this.area = area;
    }
    public Tolet(Member member, Date date, String description, Integer roomSize, Integer washroom, String title, Integer varanda, Boolean parking, double rent, String contactNumber, String email, String location, String area, String remark1, String remark2) {
       this.member = member;
       this.date = date;
       this.description = description;
       this.roomSize = roomSize;
       this.washroom = washroom;
       this.title = title;
       this.varanda = varanda;
       this.parking = parking;
       this.rent = rent;
       this.contactNumber = contactNumber;
       this.email = email;
       this.location = location;
       this.area = area;
       this.remark1 = remark1;
       this.remark2 = remark2;
    }
   
    public Integer getIdAuto() {
        return this.idAuto;
    }
    
    public void setIdAuto(Integer idAuto) {
        this.idAuto = idAuto;
    }
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getRoomSize() {
        return this.roomSize;
    }
    
    public void setRoomSize(Integer roomSize) {
        this.roomSize = roomSize;
    }
    public Integer getWashroom() {
        return this.washroom;
    }
    
    public void setWashroom(Integer washroom) {
        this.washroom = washroom;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Integer getVaranda() {
        return this.varanda;
    }
    
    public void setVaranda(Integer varanda) {
        this.varanda = varanda;
    }
    public Boolean getParking() {
        return this.parking;
    }
    
    public void setParking(Boolean parking) {
        this.parking = parking;
    }
    public double getRent() {
        return this.rent;
    }
    
    public void setRent(double rent) {
        this.rent = rent;
    }
    public String getContactNumber() {
        return this.contactNumber;
    }
    
    public void setContactNumber(String contactNumber) {
        this.contactNumber = contactNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        System.out.println(location);
        this.location = location;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public String getRemark1() {
        return this.remark1;
    }
    
    public void setRemark1(String remark1) {
        this.remark1 = remark1;
    }
    public String getRemark2() {
        return this.remark2;
    }
    
    public void setRemark2(String remark2) {
        this.remark2 = remark2;
    }




}


